apiVersion: v1
kind: LimitRange
metadata: 
  name: lr
  namespace: sd
spec:
  limits:
  - default:
      cpu: 500m
      memory: 500m
    type: Container
    defaultRequest:
      cpu: 100m
      memory: 100m
