apiVersion: v1
kind: LimitRange
metadata: 
  name: lr
  namespace: sd
spec:
  limits:
  - default:
      cpu: 500m
      memory: 500m
    defaultRequest:
      cpu: 100m
      memory: 100m
    min:
      cpu: 10m
      memory: 10m
    max:
      cpu: 700m
      memory: 700m
    type: Container
