apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
  labels:
    type: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: mypod
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx