apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx1

---

apiVersion: v1
kind: Pod
metadata:
  name: abcd
  labels:
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx