apiVersion: v1
kind: ResourceQuota
metadata:
  name: myrq
  namespace: sd
spec:
  hard:
    pods: 2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx1
  name: nginx2
  namespace: sd
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 0.1
        memory: 250Mi
      limits:
        cpu: 0.5
        memory: 500Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: myrq1
  namespace: sd
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 500Mi
    limits.cpu: "1"
    limits.memory: 1Gi
