apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytom.fullname" . }}
  labels:
    {{- include "mytom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 30008
      protocol: TCP
      name: http
  selector:
    {{- include "mytom.selectorLabels" . | nindent 4 }}
