---
 - name: This play is used to start ec2 instance
   hosts: localhost
   connection: local
   gather_facts: fasle
   tasks:
   - name: starting ec2 instance
     ec2:
      instance_ids: i-04b7f2e3ca4495db1
      region: ap-south-1
      state: running
      wait: yes
