---
 - name: This play is used to work with ec2 instance
   hosts: localhost
   connection: local
   gather_facts: fasle
   tasks:
   - name: terminating ec2 instance
     ec2:
      instance_ids: i-0ed50c0a192bb24a3
      region: ap-south-1
      state: absent
      wait: yes
