apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydep
  name: myjenkinsdep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep
  template:
    metadata:
      labels:
        app: mydep
    spec:
      containers:
      - image: subodhdere77/regapp
        name: regapp
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myjenkinsservice
  labels:
    app: mydep
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30008
  selector:
    app: mydep
