#push_image_to_dockerhub.yaml
---
- hosts: all
  gather_facts: no
  tasks:
  - name: create docker image
    command: docker image build -t subodhdere/mytom:{{BUILD_NUMBER}} .
    args:
      chdir: /opt/build

  - name: Log into DockerHub
    docker_login:
      username: subodhdere
      password: Dummypass@11
      email: subodh.dere.7@gmail.com

  - name: push docker image
    command: docker image push subodhdere/mytom:{{BUILD_NUMBER}}
