---
- hosts: all
  tasks:
  - name: delete docker image
    command: docker image rm regapp
    ignore_errors: yes

  - name: create docker image
    command: docker image build -t regapp .
    args:
      chdir: /opt/docker-ansible

  - name: tag docker image
    command: docker image tag regapp subodhdere77/regapp

  - name: Log into DockerHub
    docker_login:
      username: subodhdere77
      password: aaibaba77
      email: subodh.dere.7@gmail.com

  - name: push docker image
    command: docker image push subodhdere77/regapp
