apiVersion: v1
kind: LimitRange
metadata:
  name: lr
  namespace: dev1
spec:
  limits:
  - default:
      cpu: 200m
      memory: 200Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    min:
      cpu: 10m
      memory: 10Mi
    max:
      cpu: 300m
      memory: 300Mi
    maxLimitRequestRatio:
      memory: 2
    type: Container
