apiVersion: v1
kind: LimitRange
metadata:
  name: lr
  namespace: sd
spec:
  limits:
  - default:
      cpu: 0.2
      memory: 200Mi
    defaultRequest:
      cpu: 0.1
      memory: 100Mi
    min:
      cpu: 0.01m
      memory: 10Mi
    max:
      cpu: 0.3
      memory: 300Mi
    maxLimitRequestRatio:
      memory: 2
    type: Container
