apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydep
  labels:
    type: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: mypod
      labels:
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      subodh: dere