apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: bitnami/kubectl
    name: nginx
    command:
      - "sleep"
      - "1000"
  serviceAccountName: sa1
