apiVersion: v1
kind: Pod
metadata:
  name: my-app1
  labels:
    type: frontend
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - name: test
        mountPath: "/config"
  volumes:
  - name: test
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    type: frontend
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["shuf -i 0-100 -n 1 >> /opt/number.out"]
      volumeMounts:
      - name: test
        mountPath: "/opt"
  volumes:
  - name: test
    hostPath:
      path: /home/docker/sd
      type: Directory
