apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete    #Default is Retain
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kube"
#  nfs:
#    path: "/srv/nfs/kube"
#    server: 172.16.16.100    
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc-hostpath
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
    - name: host-volume
      mountPath: /mydata
 
 # Note:
 # kubectl patch pv pv-hostpath -p '{"spec":{"claimRef": null}}' => change pv state from release to available
